### ISSUE TITLE
Unable to install using default Composer settings

### ISSUE THREAD

**Issue by mobweb** [notmaintained/shopify_api#1]
Just wanted to let you know that installation failed using the default Composer settings:

```
$ composer.phar install
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sandeepshetty/shopify_api dev-master -> satisfiable by sandeepshetty/shopify_api dev-master.
    - sandeepshetty/shopify_api dev-master requires sandeepshetty/wcurl dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
```

After following the instructions in the link in the error report I added the following to `composer.json` and it worked: `"minimum-stability": "dev"`

Edit: Actually, I also had to change the following @ vendor/composer/autoload_real.php, Line 33:

`require $vendorDir . '/sandeepshetty/shopify_api/vendor/sandeepshetty/wcurl/wcurl.php';`
to:
`require $vendorDir . '/sandeepshetty/wcurl/wcurl.php';`

**Comment by gabemastey** [comment]
Thanks mobweb, you saved my bacon.

**Comment by aajhiggs** [comment]
This regarding the autoload problem was causing us quite a lot of grief (namely each time we ran updates via Composer, the problem manifested itself again). I have refactored it into a class, along with a fork of wcurl with the intention of getting rid of the problem and getting them to meet PSR-0 standards. I was kind of amazed this hasn't been a problem for many others; is really no one using the PHP Shopify API and Composer?

The code is not in production environment (so probably buggy), and because it is a significant change of code, I've not requested a pull. However, @sandeepshetty, if you'd like me to I'd be happy to put one in and close this branch. It does however remove some of the legacy stuff and increase the min PHP requirement. If you (or anyone else) are  interested, the link is http://github.com/higgsdesign/ShopifyApi

**Comment by sandeepshetty** [comment]
I'll look into this sometime in the next 48 hrs and get back to you.

**Comment by danboudwin** [comment]
Hi Sandeep!

Thanks for making the changes to smooth the process of loading via composer.

I'm having 1 last issue that I'm hoping you can address. Not sure if it's related to the framework I'm using (Laravel 4) or it's a more global issue but I'm having an issue with the line...

require 'vendor/autoload.php'; 

in \shopify_api\client.php.

If I remove the line everything is working as expected in my initial testing.

Let me know you thoughts on this.  Is this line required for installations in other frameworks?

Thanks,

Dan

**Comment by sandeepshetty** [comment]
@seamlss This looks likes it's left over from the time client.php was responsible for pulling in it's dependencies. Now that the composer autoloader is taking care of it, it can be removed. 

This problem is specific to non-OO stuff using composer and I'm still trying to decide between the code or composer pulling in the dependencies. I'm leaning toward the code doing it (unlike the current implementation) because it makes it explicit in the code (where it actually matters).

Give me day or two to think about this. I'm open to any suggestions you all might have.

**Comment by danboudwin** [comment]
I would agree that the more explicit the better my only concern is that any paths are done in such a way that it still allows for plug and play installation no matter what framework (of no framework) someone is using. I'm still figuring out creating composer packages tho myself so take my opinions with that in mind! 

Let me know if you'd like help testing out whichever direction you decide to take.

**Comment by sandeepshetty** [comment]
See http://www.sandeep.io/128

Will be implementing that soon.

**Comment by RashmiTerkhedkar** [comment]
I am trying to use sandeepshetty/shopify_api I have installed it on local and then uploaded it on live.

it was working fine  before somedays but now when try to install same shopify  app then getting error like 
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /hsphere/local/home/test.com/shopify/shopify_testing/shopify_app1.php on line 4

code--->
<?php
ini_set("display_errors","on");
require 'vendor/autoload.php';
use sandeepshetty\shopify_api;
?>

**Comment by sandeepshetty** [comment]
This issue and more fixed in the [latest version](https://github.com/phpish/shopify)
